# Generated by Django 4.2.16 on 2024-10-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0004_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='4g8h6fTZSQ2e7eni43cRXS0MNzUjfFZQ', editable=False, max_length=32, unique=True),
        ),
    ]
